# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on:
  push:
    branches: [ "main", "sca-colin" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
  sca:

    runs-on: ubuntu-latest

    steps:

    - name: Create SBOM
      uses: anchore/sbom-action@v0
      with:
        format: spdx-json
        output-file: "${{ github.event.repository.name }}-sbom.spdx.json"


    - name: Scan SBOM
      uses: anchore/scan-action@v7
      with:
        path: "."
        fail-build: true
        severity-cutoff: critical

        



   